services:
  postgres:
    image: postgres:16-alpine
    container_name: bicipop-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16-alpine
    container_name: bicipop-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: bicipop
      POSTGRES_PASSWORD: bicipop_secret
      POSTGRES_DB: bicipop_test_db
    ports:
      - '5433:5432'

volumes:
  postgres_data:
